# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T11:10:47+00:00

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Any, Dict, List, Optional

from pydantic import AnyUrl, BaseModel, Field, constr


class InteractionEnumResourceStatus(Enum):
    accepted = 'accepted'
    answered = 'answered'
    busy = 'busy'
    canceled = 'canceled'
    completed = 'completed'
    deleted = 'deleted'
    delivered = 'delivered'
    delivery_unknown = 'delivery-unknown'
    failed = 'failed'
    in_progress = 'in-progress'
    initiated = 'initiated'
    no_answer = 'no-answer'
    queued = 'queued'
    received = 'received'
    receiving = 'receiving'
    ringing = 'ringing'
    scheduled = 'scheduled'
    sending = 'sending'
    sent = 'sent'
    undelivered = 'undelivered'
    unknown = 'unknown'


class InteractionEnumType(Enum):
    message = 'message'
    voice = 'voice'
    unknown = 'unknown'


class MessageInteractionEnumResourceStatus(Enum):
    accepted = 'accepted'
    answered = 'answered'
    busy = 'busy'
    canceled = 'canceled'
    completed = 'completed'
    deleted = 'deleted'
    delivered = 'delivered'
    delivery_unknown = 'delivery-unknown'
    failed = 'failed'
    in_progress = 'in-progress'
    initiated = 'initiated'
    no_answer = 'no-answer'
    queued = 'queued'
    received = 'received'
    receiving = 'receiving'
    ringing = 'ringing'
    scheduled = 'scheduled'
    sending = 'sending'
    sent = 'sent'
    undelivered = 'undelivered'
    unknown = 'unknown'


class MessageInteractionEnumType(Enum):
    message = 'message'
    voice = 'voice'
    unknown = 'unknown'


class Capabilities(BaseModel):
    fax: Optional[bool] = None
    mms: Optional[bool] = None
    sms: Optional[bool] = None
    voice: Optional[bool] = None


class ProxyV1ServicePhoneNumber(BaseModel):
    account_sid: Optional[
        constr(pattern=r'^AC[0-9a-fA-F]{32}$', min_length=34, max_length=34)
    ] = Field(
        None,
        description='The SID of the [Account](https://www.twilio.com/docs/iam/api/account) that created the PhoneNumber resource.',
    )
    capabilities: Optional[Capabilities] = Field(
        None, description='The capabilities of the phone number.'
    )
    date_created: Optional[datetime] = Field(
        None,
        description='The [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) date and time in GMT when the resource was created.',
    )
    date_updated: Optional[datetime] = Field(
        None,
        description='The [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) date and time in GMT when the resource was last updated.',
    )
    friendly_name: Optional[str] = Field(
        None, description='The string that you assigned to describe the resource.'
    )
    in_use: Optional[int] = Field(
        None,
        description='The number of open session assigned to the number. See the [How many Phone Numbers do I need?](https://www.twilio.com/docs/proxy/phone-numbers-needed) guide for more information.',
    )
    is_reserved: Optional[bool] = Field(
        None,
        description='Whether the phone number should be reserved and not be assigned to a participant using proxy pool logic. See [Reserved Phone Numbers](https://www.twilio.com/docs/proxy/reserved-phone-numbers) for more information.',
    )
    iso_country: Optional[str] = Field(
        None, description='The ISO Country Code for the phone number.'
    )
    phone_number: Optional[str] = Field(
        None,
        description='The phone number in [E.164](https://www.twilio.com/docs/glossary/what-e164) format, which consists of a + followed by the country code and subscriber number.',
    )
    service_sid: Optional[
        constr(pattern=r'^KS[0-9a-fA-F]{32}$', min_length=34, max_length=34)
    ] = Field(
        None,
        description="The SID of the PhoneNumber resource's parent [Service](https://www.twilio.com/docs/proxy/api/service) resource.",
    )
    sid: Optional[
        constr(pattern=r'^PN[0-9a-fA-F]{32}$', min_length=34, max_length=34)
    ] = Field(
        None,
        description='The unique string that we created to identify the PhoneNumber resource.',
    )
    url: Optional[AnyUrl] = Field(
        None, description='The absolute URL of the PhoneNumber resource.'
    )


class ProxyV1ServiceSessionInteraction(BaseModel):
    account_sid: Optional[
        constr(pattern=r'^AC[0-9a-fA-F]{32}$', min_length=34, max_length=34)
    ] = Field(
        None,
        description='The SID of the [Account](https://www.twilio.com/docs/iam/api/account) that created the Interaction resource.',
    )
    data: Optional[str] = Field(
        None,
        description='A JSON string that includes the message body of message interactions (e.g. `{"body": "hello"}`) or the call duration (when available) of a call (e.g. `{"duration": "5"}`).',
    )
    date_created: Optional[datetime] = Field(
        None,
        description='The [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) date and time in GMT when the Interaction was created.',
    )
    date_updated: Optional[datetime] = Field(
        None,
        description='The [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) date and time in GMT when the resource was last updated.',
    )
    inbound_participant_sid: Optional[
        constr(pattern=r'^KP[0-9a-fA-F]{32}$', min_length=34, max_length=34)
    ] = Field(
        None,
        description='The SID of the inbound [Participant](https://www.twilio.com/docs/proxy/api/participant) resource.',
    )
    inbound_resource_sid: Optional[
        constr(pattern=r'^[a-zA-Z]{2}[0-9a-fA-F]{32}$', min_length=34, max_length=34)
    ] = Field(
        None,
        description='The SID of the inbound resource; either the [Call](https://www.twilio.com/docs/voice/api/call-resource) or [Message](https://www.twilio.com/docs/sms/api/message.',
    )
    inbound_resource_status: Optional[InteractionEnumResourceStatus] = Field(
        None,
        description='The inbound resource status of the Interaction. Will always be `delivered` for messages and `in-progress` for calls.',
    )
    inbound_resource_type: Optional[str] = Field(
        None,
        description='The inbound resource type. Can be [Call](https://www.twilio.com/docs/voice/api/call-resource) or [Message](https://www.twilio.com/docs/sms/api/message-resource).',
    )
    inbound_resource_url: Optional[AnyUrl] = Field(
        None, description='The URL of the Twilio inbound resource'
    )
    outbound_participant_sid: Optional[
        constr(pattern=r'^KP[0-9a-fA-F]{32}$', min_length=34, max_length=34)
    ] = Field(
        None,
        description='The SID of the outbound [Participant](https://www.twilio.com/docs/proxy/api/participant)).',
    )
    outbound_resource_sid: Optional[
        constr(pattern=r'^[a-zA-Z]{2}[0-9a-fA-F]{32}$', min_length=34, max_length=34)
    ] = Field(
        None,
        description='The SID of the outbound resource; either the [Call](https://www.twilio.com/docs/voice/api/call-resource) or [Message](https://www.twilio.com/docs/sms/api/message-resource).',
    )
    outbound_resource_status: Optional[InteractionEnumResourceStatus] = Field(
        None,
        description='The outbound resource status of the Interaction. Can be: `accepted`, `canceled`, `deleted`, `delivered`, `delivery-unknown`, `failed`, `partially-delivered`, `queued`, `read`, `received`, `receiving`, `scheduled`, `sending`, `sent`, `undelivered`, or `unknown` for messages.  Can be `initiated` or `completed` or `unknown` for calls.',
    )
    outbound_resource_type: Optional[str] = Field(
        None,
        description='The outbound resource type. Can be: [Call](https://www.twilio.com/docs/voice/api/call-resource) or [Message](https://www.twilio.com/docs/sms/api/message-resource).',
    )
    outbound_resource_url: Optional[AnyUrl] = Field(
        None, description='The URL of the Twilio outbound resource.'
    )
    service_sid: Optional[
        constr(pattern=r'^KS[0-9a-fA-F]{32}$', min_length=34, max_length=34)
    ] = Field(
        None,
        description='The SID of the parent [Service](https://www.twilio.com/docs/proxy/api/service) resource.',
    )
    session_sid: Optional[
        constr(pattern=r'^KC[0-9a-fA-F]{32}$', min_length=34, max_length=34)
    ] = Field(
        None,
        description='The SID of the parent [Session](https://www.twilio.com/docs/proxy/api/session) resource.',
    )
    sid: Optional[
        constr(pattern=r'^KI[0-9a-fA-F]{32}$', min_length=34, max_length=34)
    ] = Field(
        None,
        description='The unique string that we created to identify the Interaction resource.',
    )
    type: Optional[InteractionEnumType] = Field(
        None,
        description='The Type of the Interaction. Can be: `message`, `voice` or `unknown`.',
    )
    url: Optional[AnyUrl] = Field(
        None, description='The absolute URL of the Interaction resource.'
    )


class ProxyV1ServiceSessionParticipant(BaseModel):
    account_sid: Optional[
        constr(pattern=r'^AC[0-9a-fA-F]{32}$', min_length=34, max_length=34)
    ] = Field(
        None,
        description='The SID of the [Account](https://www.twilio.com/docs/iam/api/account) that created the Participant resource.',
    )
    date_created: Optional[datetime] = Field(
        None,
        description='The [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) date and time in GMT when the resource was created.',
    )
    date_deleted: Optional[datetime] = Field(
        None,
        description='The [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) date when the Participant was removed from the session.',
    )
    date_updated: Optional[datetime] = Field(
        None,
        description='The [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) date and time in GMT when the resource was last updated.',
    )
    friendly_name: Optional[str] = Field(
        None,
        description='The string that you assigned to describe the participant. This value must be 255 characters or fewer. Supports UTF-8 characters. **This value should not have PII.**',
    )
    identifier: Optional[str] = Field(
        None,
        description='The phone number or channel identifier of the Participant. This value must be 191 characters or fewer. Supports UTF-8 characters.',
    )
    links: Optional[Dict[str, Any]] = Field(
        None, description='The URLs to resources related the participant.'
    )
    proxy_identifier: Optional[str] = Field(
        None,
        description="The phone number or short code (masked number) of the participant's partner. The participant will call or message the partner participant at this number.",
    )
    proxy_identifier_sid: Optional[
        constr(pattern=r'^PN[0-9a-fA-F]{32}$', min_length=34, max_length=34)
    ] = Field(
        None, description='The SID of the Proxy Identifier assigned to the Participant.'
    )
    service_sid: Optional[
        constr(pattern=r'^KS[0-9a-fA-F]{32}$', min_length=34, max_length=34)
    ] = Field(
        None,
        description="The SID of the resource's parent [Service](https://www.twilio.com/docs/proxy/api/service) resource.",
    )
    session_sid: Optional[
        constr(pattern=r'^KC[0-9a-fA-F]{32}$', min_length=34, max_length=34)
    ] = Field(
        None,
        description='The SID of the parent [Session](https://www.twilio.com/docs/proxy/api/session) resource.',
    )
    sid: Optional[
        constr(pattern=r'^KP[0-9a-fA-F]{32}$', min_length=34, max_length=34)
    ] = Field(
        None,
        description='The unique string that we created to identify the Participant resource.',
    )
    url: Optional[AnyUrl] = Field(
        None, description='The absolute URL of the Participant resource.'
    )


class ProxyV1ServiceSessionParticipantMessageInteraction(BaseModel):
    account_sid: Optional[
        constr(pattern=r'^AC[0-9a-fA-F]{32}$', min_length=34, max_length=34)
    ] = Field(
        None,
        description='The SID of the [Account](https://www.twilio.com/docs/iam/api/account) that created the MessageInteraction resource.',
    )
    data: Optional[str] = Field(
        None,
        description='A JSON string that includes the message body sent to the participant. (e.g. `{"body": "hello"}`)',
    )
    date_created: Optional[datetime] = Field(
        None,
        description='The [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) date and time in GMT when the resource was created.',
    )
    date_updated: Optional[datetime] = Field(
        None,
        description='The [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) date and time in GMT when the resource was last updated.',
    )
    inbound_participant_sid: Optional[
        constr(pattern=r'^KP[0-9a-fA-F]{32}$', min_length=34, max_length=34)
    ] = Field(None, description='Always empty for created Message Interactions.')
    inbound_resource_sid: Optional[
        constr(pattern=r'^[a-zA-Z]{2}[0-9a-fA-F]{32}$', min_length=34, max_length=34)
    ] = Field(None, description='Always empty for created Message Interactions.')
    inbound_resource_status: Optional[MessageInteractionEnumResourceStatus] = Field(
        None, description='Always empty for created Message Interactions.'
    )
    inbound_resource_type: Optional[str] = Field(
        None, description='Always empty for created Message Interactions.'
    )
    inbound_resource_url: Optional[AnyUrl] = Field(
        None, description='Always empty for created Message Interactions.'
    )
    outbound_participant_sid: Optional[
        constr(pattern=r'^KP[0-9a-fA-F]{32}$', min_length=34, max_length=34)
    ] = Field(
        None,
        description='The SID of the outbound [Participant](https://www.twilio.com/docs/proxy/api/participant) resource.',
    )
    outbound_resource_sid: Optional[
        constr(pattern=r'^[a-zA-Z]{2}[0-9a-fA-F]{32}$', min_length=34, max_length=34)
    ] = Field(
        None,
        description='The SID of the outbound [Message](https://www.twilio.com/docs/sms/api/message-resource) resource.',
    )
    outbound_resource_status: Optional[MessageInteractionEnumResourceStatus] = Field(
        None,
        description='The outbound message resource status. Can be: `accepted`, `deleted`, `delivered`, `delivery-unknown`, `failed`, `queued`, `received`, `receiving`, `scheduled`, `sending`, `sent`, `undelivered`, or `unknown`.',
    )
    outbound_resource_type: Optional[str] = Field(
        None, description='The outbound resource type. This value is always `Message`.'
    )
    outbound_resource_url: Optional[AnyUrl] = Field(
        None, description='The URL of the Twilio message resource.'
    )
    participant_sid: Optional[
        constr(pattern=r'^KP[0-9a-fA-F]{32}$', min_length=34, max_length=34)
    ] = Field(
        None,
        description='The SID of the [Participant](https://www.twilio.com/docs/proxy/api/participant) resource.',
    )
    service_sid: Optional[
        constr(pattern=r'^KS[0-9a-fA-F]{32}$', min_length=34, max_length=34)
    ] = Field(
        None,
        description='The SID of the parent [Service](https://www.twilio.com/docs/proxy/api/service) resource.',
    )
    session_sid: Optional[
        constr(pattern=r'^KC[0-9a-fA-F]{32}$', min_length=34, max_length=34)
    ] = Field(
        None,
        description='The SID of the parent [Session](https://www.twilio.com/docs/proxy/api/session) resource.',
    )
    sid: Optional[
        constr(pattern=r'^KI[0-9a-fA-F]{32}$', min_length=34, max_length=34)
    ] = Field(
        None,
        description='The unique string that we created to identify the MessageInteraction resource.',
    )
    type: Optional[MessageInteractionEnumType] = Field(
        None,
        description='The Type of Message Interaction. This value is always `message`.',
    )
    url: Optional[AnyUrl] = Field(
        None, description='The absolute URL of the MessageInteraction resource.'
    )


class ProxyV1ServiceShortCode(BaseModel):
    account_sid: Optional[
        constr(pattern=r'^AC[0-9a-fA-F]{32}$', min_length=34, max_length=34)
    ] = Field(
        None,
        description='The SID of the [Account](https://www.twilio.com/docs/iam/api/account) that created the ShortCode resource.',
    )
    capabilities: Optional[Capabilities] = Field(
        None, description='The capabilities of the short code.'
    )
    date_created: Optional[datetime] = Field(
        None,
        description='The [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) date and time in GMT when the resource was created.',
    )
    date_updated: Optional[datetime] = Field(
        None,
        description='The [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) date and time in GMT when the resource was last updated.',
    )
    is_reserved: Optional[bool] = Field(
        None,
        description='Whether the short code should be reserved and not be assigned to a participant using proxy pool logic. See [Reserved Phone Numbers](https://www.twilio.com/docs/proxy/reserved-phone-numbers) for more information.',
    )
    iso_country: Optional[str] = Field(
        None, description='The ISO Country Code for the short code.'
    )
    service_sid: Optional[
        constr(pattern=r'^KS[0-9a-fA-F]{32}$', min_length=34, max_length=34)
    ] = Field(
        None,
        description="The SID of the ShortCode resource's parent [Service](https://www.twilio.com/docs/proxy/api/service) resource.",
    )
    short_code: Optional[str] = Field(None, description="The short code's number.")
    sid: Optional[
        constr(pattern=r'^SC[0-9a-fA-F]{32}$', min_length=34, max_length=34)
    ] = Field(
        None,
        description='The unique string that we created to identify the ShortCode resource.',
    )
    url: Optional[AnyUrl] = Field(
        None, description='The absolute URL of the ShortCode resource.'
    )


class ServiceEnumGeoMatchLevel(Enum):
    area_code = 'area-code'
    overlay = 'overlay'
    radius = 'radius'
    country = 'country'


class ServiceEnumNumberSelectionBehavior(Enum):
    avoid_sticky = 'avoid-sticky'
    prefer_sticky = 'prefer-sticky'


class SessionEnumMode(Enum):
    message_only = 'message-only'
    voice_only = 'voice-only'
    voice_and_message = 'voice-and-message'


class SessionEnumStatus(Enum):
    open = 'open'
    in_progress = 'in-progress'
    closed = 'closed'
    failed = 'failed'
    unknown = 'unknown'


class Meta(BaseModel):
    first_page_url: Optional[AnyUrl] = None
    key: Optional[str] = None
    next_page_url: Optional[AnyUrl] = None
    page: Optional[int] = None
    page_size: Optional[int] = None
    previous_page_url: Optional[AnyUrl] = None
    url: Optional[AnyUrl] = None


class V1ServicesPostRequest(BaseModel):
    CallbackUrl: Optional[AnyUrl] = Field(
        None, description='The URL we should call when the interaction status changes.'
    )
    ChatInstanceSid: Optional[
        constr(pattern=r'^IS[0-9a-fA-F]{32}$', min_length=34, max_length=34)
    ] = Field(
        None,
        description='The SID of the Chat Service Instance managed by Proxy Service. The Chat Service enables Proxy to forward SMS and channel messages to this chat instance. This is a one-to-one relationship.',
    )
    DefaultTtl: Optional[int] = Field(
        None,
        description="The default `ttl` value to set for Sessions created in the Service. The TTL (time to live) is measured in seconds after the Session's last create or last Interaction. The default value of `0` indicates an unlimited Session length. You can override a Session's default TTL value by setting its `ttl` value.",
    )
    GeoMatchLevel: Optional[ServiceEnumGeoMatchLevel] = Field(
        None,
        description='Where a proxy number must be located relative to the participant identifier. Can be: `country`, `area-code`, or `extended-area-code`. The default value is `country` and more specific areas than `country` are only available in North America.',
    )
    InterceptCallbackUrl: Optional[AnyUrl] = Field(
        None,
        description='The URL we call on each interaction. If we receive a 403 status, we block the interaction; otherwise the interaction continues.',
    )
    NumberSelectionBehavior: Optional[ServiceEnumNumberSelectionBehavior] = Field(
        None,
        description='The preference for Proxy Number selection in the Service instance. Can be: `prefer-sticky` or `avoid-sticky` and the default is `prefer-sticky`. `prefer-sticky` means that we will try and select the same Proxy Number for a given participant if they have previous [Sessions](https://www.twilio.com/docs/proxy/api/session), but we will not fail if that Proxy Number cannot be used.  `avoid-sticky` means that we will try to use different Proxy Numbers as long as that is possible within a given pool rather than try and use a previously assigned number.',
    )
    OutOfSessionCallbackUrl: Optional[AnyUrl] = Field(
        None,
        description='The URL we should call when an inbound call or SMS action occurs on a closed or non-existent Session. If your server (or a Twilio [function](https://www.twilio.com/functions)) responds with valid [TwiML](https://www.twilio.com/docs/voice/twiml), we will process it. This means it is possible, for example, to play a message for a call, send an automated text message response, or redirect a call to another Phone Number. See [Out-of-Session Callback Response Guide](https://www.twilio.com/docs/proxy/out-session-callback-response-guide) for more information.',
    )
    UniqueName: str = Field(
        ...,
        description='An application-defined string that uniquely identifies the resource. This value must be 191 characters or fewer in length and be unique. **This value should not have PII.**',
    )


class V1ServicesServiceSidPhoneNumbersGetResponse(BaseModel):
    meta: Optional[Meta] = None
    phone_numbers: Optional[List[ProxyV1ServicePhoneNumber]] = None


class V1ServicesServiceSidPhoneNumbersPostRequest(BaseModel):
    IsReserved: Optional[bool] = Field(
        None,
        description='Whether the new phone number should be reserved and not be assigned to a participant using proxy pool logic. See [Reserved Phone Numbers](https://www.twilio.com/docs/proxy/reserved-phone-numbers) for more information.',
    )
    PhoneNumber: Optional[str] = Field(
        None,
        description='The phone number in [E.164](https://www.twilio.com/docs/glossary/what-e164) format.  E.164 phone numbers consist of a + followed by the country code and subscriber number without punctuation characters. For example, +14155551234.',
    )
    Sid: Optional[
        constr(pattern=r'^PN[0-9a-fA-F]{32}$', min_length=34, max_length=34)
    ] = Field(
        None,
        description='The SID of a Twilio [IncomingPhoneNumber](https://www.twilio.com/docs/phone-numbers/api/incomingphonenumber-resource) resource that represents the Twilio Number you would like to assign to your Proxy Service.',
    )


class V1ServicesServiceSidPhoneNumbersSidPostRequest(BaseModel):
    IsReserved: Optional[bool] = Field(
        None,
        description='Whether the phone number should be reserved and not be assigned to a participant using proxy pool logic. See [Reserved Phone Numbers](https://www.twilio.com/docs/proxy/reserved-phone-numbers) for more information.',
    )


class V1ServicesServiceSidSessionsPostRequest(BaseModel):
    DateExpiry: Optional[datetime] = Field(
        None,
        description='The [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) date when the Session should expire. If this is value is present, it overrides the `ttl` value.',
    )
    Mode: Optional[SessionEnumMode] = Field(
        None,
        description='The Mode of the Session. Can be: `message-only`, `voice-only`, or `voice-and-message` and the default value is `voice-and-message`.',
    )
    Participants: Optional[List] = Field(
        None, description='The Participant objects to include in the new session.'
    )
    Status: Optional[SessionEnumStatus] = Field(
        None,
        description='The initial status of the Session. Can be: `open`, `in-progress`, `closed`, `failed`, or `unknown`. The default is `open` on create.',
    )
    Ttl: Optional[int] = Field(
        None,
        description="The time, in seconds, when the session will expire. The time is measured from the last Session create or the Session's last Interaction.",
    )
    UniqueName: Optional[str] = Field(
        None,
        description='An application-defined string that uniquely identifies the resource. This value must be 191 characters or fewer in length and be unique. **This value should not have PII.**',
    )


class V1ServicesServiceSidSessionsSessionSidInteractionsGetResponse(BaseModel):
    interactions: Optional[List[ProxyV1ServiceSessionInteraction]] = None
    meta: Optional[Meta] = None


class V1ServicesServiceSidSessionsSessionSidParticipantsGetResponse(BaseModel):
    meta: Optional[Meta] = None
    participants: Optional[List[ProxyV1ServiceSessionParticipant]] = None


class V1ServicesServiceSidSessionsSessionSidParticipantsPostRequest(BaseModel):
    FriendlyName: Optional[str] = Field(
        None,
        description='The string that you assigned to describe the participant. This value must be 255 characters or fewer. **This value should not have PII.**',
    )
    Identifier: str = Field(..., description='The phone number of the Participant.')
    ProxyIdentifier: Optional[str] = Field(
        None,
        description='The proxy phone number to use for the Participant. If not specified, Proxy will select a number from the pool.',
    )
    ProxyIdentifierSid: Optional[
        constr(pattern=r'^PN[0-9a-fA-F]{32}$', min_length=34, max_length=34)
    ] = Field(
        None,
        description='The SID of the Proxy Identifier to assign to the Participant.',
    )


class V1ServicesServiceSidSessionsSessionSidParticipantsParticipantSidMessageInteractionsGetResponse(
    BaseModel
):
    interactions: Optional[List[ProxyV1ServiceSessionParticipantMessageInteraction]] = (
        None
    )
    meta: Optional[Meta] = None


class V1ServicesServiceSidSessionsSessionSidParticipantsParticipantSidMessageInteractionsPostRequest(
    BaseModel
):
    Body: Optional[str] = Field(
        None, description='The message to send to the participant'
    )
    MediaUrl: Optional[List[AnyUrl]] = Field(
        None, description='Reserved. Not currently supported.'
    )


class V1ServicesServiceSidSessionsSidPostRequest(BaseModel):
    DateExpiry: Optional[datetime] = Field(
        None,
        description='The [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) date when the Session should expire. If this is value is present, it overrides the `ttl` value.',
    )
    Status: Optional[SessionEnumStatus] = Field(
        None,
        description='The new status of the resource. Can be: `in-progress` to re-open a session or `closed` to close a session.',
    )
    Ttl: Optional[int] = Field(
        None,
        description="The time, in seconds, when the session will expire. The time is measured from the last Session create or the Session's last Interaction.",
    )


class V1ServicesServiceSidShortCodesGetResponse(BaseModel):
    meta: Optional[Meta] = None
    short_codes: Optional[List[ProxyV1ServiceShortCode]] = None


class V1ServicesServiceSidShortCodesPostRequest(BaseModel):
    Sid: constr(pattern=r'^SC[0-9a-fA-F]{32}$', min_length=34, max_length=34) = Field(
        ...,
        description='The SID of a Twilio [ShortCode](https://www.twilio.com/docs/sms/api/short-code) resource that represents the short code you would like to assign to your Proxy Service.',
    )


class V1ServicesServiceSidShortCodesSidPostRequest(BaseModel):
    IsReserved: Optional[bool] = Field(
        None,
        description='Whether the short code should be reserved and not be assigned to a participant using proxy pool logic. See [Reserved Phone Numbers](https://www.twilio.com/docs/proxy/reserved-phone-numbers) for more information.',
    )


class V1ServicesSidPostRequest(BaseModel):
    CallbackUrl: Optional[AnyUrl] = Field(
        None, description='The URL we should call when the interaction status changes.'
    )
    ChatInstanceSid: Optional[
        constr(pattern=r'^IS[0-9a-fA-F]{32}$', min_length=34, max_length=34)
    ] = Field(
        None,
        description='The SID of the Chat Service Instance managed by Proxy Service. The Chat Service enables Proxy to forward SMS and channel messages to this chat instance. This is a one-to-one relationship.',
    )
    DefaultTtl: Optional[int] = Field(
        None,
        description="The default `ttl` value to set for Sessions created in the Service. The TTL (time to live) is measured in seconds after the Session's last create or last Interaction. The default value of `0` indicates an unlimited Session length. You can override a Session's default TTL value by setting its `ttl` value.",
    )
    GeoMatchLevel: Optional[ServiceEnumGeoMatchLevel] = Field(
        None,
        description='Where a proxy number must be located relative to the participant identifier. Can be: `country`, `area-code`, or `extended-area-code`. The default value is `country` and more specific areas than `country` are only available in North America.',
    )
    InterceptCallbackUrl: Optional[AnyUrl] = Field(
        None,
        description='The URL we call on each interaction. If we receive a 403 status, we block the interaction; otherwise the interaction continues.',
    )
    NumberSelectionBehavior: Optional[ServiceEnumNumberSelectionBehavior] = Field(
        None,
        description='The preference for Proxy Number selection in the Service instance. Can be: `prefer-sticky` or `avoid-sticky` and the default is `prefer-sticky`. `prefer-sticky` means that we will try and select the same Proxy Number for a given participant if they have previous [Sessions](https://www.twilio.com/docs/proxy/api/session), but we will not fail if that Proxy Number cannot be used.  `avoid-sticky` means that we will try to use different Proxy Numbers as long as that is possible within a given pool rather than try and use a previously assigned number.',
    )
    OutOfSessionCallbackUrl: Optional[AnyUrl] = Field(
        None,
        description='The URL we should call when an inbound call or SMS action occurs on a closed or non-existent Session. If your server (or a Twilio [function](https://www.twilio.com/functions)) responds with valid [TwiML](https://www.twilio.com/docs/voice/twiml), we will process it. This means it is possible, for example, to play a message for a call, send an automated text message response, or redirect a call to another Phone Number. See [Out-of-Session Callback Response Guide](https://www.twilio.com/docs/proxy/out-session-callback-response-guide) for more information.',
    )
    UniqueName: Optional[str] = Field(
        None,
        description='An application-defined string that uniquely identifies the resource. This value must be 191 characters or fewer in length and be unique. **This value should not have PII.**',
    )


class ProxyV1Service(BaseModel):
    account_sid: Optional[
        constr(pattern=r'^AC[0-9a-fA-F]{32}$', min_length=34, max_length=34)
    ] = Field(
        None,
        description='The SID of the [Account](https://www.twilio.com/docs/iam/api/account) that created the Service resource.',
    )
    callback_url: Optional[AnyUrl] = Field(
        None, description='The URL we call when the interaction status changes.'
    )
    chat_instance_sid: Optional[
        constr(pattern=r'^IS[0-9a-fA-F]{32}$', min_length=34, max_length=34)
    ] = Field(
        None,
        description='The SID of the Chat Service Instance managed by Proxy Service. The Chat Service enables Proxy to forward SMS and channel messages to this chat instance. This is a one-to-one relationship.',
    )
    date_created: Optional[datetime] = Field(
        None,
        description='The [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) date and time in GMT when the resource was created.',
    )
    date_updated: Optional[datetime] = Field(
        None,
        description='The [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) date and time in GMT when the resource was last updated.',
    )
    default_ttl: Optional[int] = Field(
        None,
        description="The default `ttl` value for Sessions created in the Service. The TTL (time to live) is measured in seconds after the Session's last create or last Interaction. The default value of `0` indicates an unlimited Session length. You can override a Session's default TTL value by setting its `ttl` value.",
    )
    geo_match_level: Optional[ServiceEnumGeoMatchLevel] = Field(
        None,
        description='Where a proxy number must be located relative to the participant identifier. Can be: `country`, `area-code`, or `extended-area-code`. The default value is `country` and more specific areas than `country` are only available in North America.',
    )
    intercept_callback_url: Optional[AnyUrl] = Field(
        None,
        description='The URL we call on each interaction. If we receive a 403 status, we block the interaction; otherwise the interaction continues.',
    )
    links: Optional[Dict[str, Any]] = Field(
        None, description='The URLs of resources related to the Service.'
    )
    number_selection_behavior: Optional[ServiceEnumNumberSelectionBehavior] = Field(
        None,
        description='The preference for Proxy Number selection in the Service instance. Can be: `prefer-sticky` or `avoid-sticky`. `prefer-sticky` means that we will try and select the same Proxy Number for a given participant if they have previous [Sessions](https://www.twilio.com/docs/proxy/api/session), but we will not fail if that Proxy Number cannot be used.  `avoid-sticky` means that we will try to use different Proxy Numbers as long as that is possible within a given pool rather than try and use a previously assigned number.',
    )
    out_of_session_callback_url: Optional[AnyUrl] = Field(
        None,
        description='The URL we call when an inbound call or SMS action occurs on a closed or non-existent Session. If your server (or a Twilio [function](https://www.twilio.com/functions)) responds with valid [TwiML](https://www.twilio.com/docs/voice/twiml), we will process it. This means it is possible, for example, to play a message for a call, send an automated text message response, or redirect a call to another Phone Number. See [Out-of-Session Callback Response Guide](https://www.twilio.com/docs/proxy/out-session-callback-response-guide) for more information.',
    )
    sid: Optional[
        constr(pattern=r'^KS[0-9a-fA-F]{32}$', min_length=34, max_length=34)
    ] = Field(
        None,
        description='The unique string that we created to identify the Service resource.',
    )
    unique_name: Optional[str] = Field(
        None,
        description='An application-defined string that uniquely identifies the resource. This value must be 191 characters or fewer in length and be unique. Supports UTF-8 characters. **This value should not have PII.**',
    )
    url: Optional[AnyUrl] = Field(
        None, description='The absolute URL of the Service resource.'
    )


class ProxyV1ServiceSession(BaseModel):
    account_sid: Optional[
        constr(pattern=r'^AC[0-9a-fA-F]{32}$', min_length=34, max_length=34)
    ] = Field(
        None,
        description='The SID of the [Account](https://www.twilio.com/docs/iam/api/account) that created the Session resource.',
    )
    closed_reason: Optional[str] = Field(
        None, description='The reason the Session ended.'
    )
    date_created: Optional[datetime] = Field(
        None,
        description='The [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) date and time in GMT when the resource was created.',
    )
    date_ended: Optional[datetime] = Field(
        None,
        description='The [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) date when the Session ended.',
    )
    date_expiry: Optional[datetime] = Field(
        None,
        description='The [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) date when the Session should expire. If this is value is present, it overrides the `ttl` value.',
    )
    date_last_interaction: Optional[datetime] = Field(
        None,
        description='The [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) date when the Session last had an interaction.',
    )
    date_started: Optional[datetime] = Field(
        None,
        description='The [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) date when the Session started.',
    )
    date_updated: Optional[datetime] = Field(
        None,
        description='The [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) date and time in GMT when the resource was last updated.',
    )
    links: Optional[Dict[str, Any]] = Field(
        None, description='The URLs of resources related to the Session.'
    )
    mode: Optional[SessionEnumMode] = Field(
        None,
        description='The Mode of the Session. Can be: `message-only`, `voice-only`, or `voice-and-message`.',
    )
    service_sid: Optional[
        constr(pattern=r'^KS[0-9a-fA-F]{32}$', min_length=34, max_length=34)
    ] = Field(
        None,
        description='The SID of the [Service](https://www.twilio.com/docs/proxy/api/service) the session is associated with.',
    )
    sid: Optional[
        constr(pattern=r'^KC[0-9a-fA-F]{32}$', min_length=34, max_length=34)
    ] = Field(
        None,
        description='The unique string that we created to identify the Session resource.',
    )
    status: Optional[SessionEnumStatus] = Field(
        None,
        description='The status of the Session. Can be: `open`, `in-progress`, `closed`, `failed`, or `unknown`.',
    )
    ttl: Optional[int] = Field(
        None,
        description="The time, in seconds, when the session will expire. The time is measured from the last Session create or the Session's last Interaction.",
    )
    unique_name: Optional[str] = Field(
        None,
        description='An application-defined string that uniquely identifies the resource. This value must be 191 characters or fewer in length and be unique. Supports UTF-8 characters. **This value should not have PII.**',
    )
    url: Optional[AnyUrl] = Field(
        None, description='The absolute URL of the Session resource.'
    )


class V1ServicesGetResponse(BaseModel):
    meta: Optional[Meta] = None
    services: Optional[List[ProxyV1Service]] = None


class V1ServicesServiceSidSessionsGetResponse(BaseModel):
    meta: Optional[Meta] = None
    sessions: Optional[List[ProxyV1ServiceSession]] = None
